version: '3.8'

services:
  api_app:
    container_name: api_app
    image: api-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/mysql?useSSL=false  # Cambiado localhost a mysql
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0.40
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
